<!DOCTYPE html>
<html>
<head>
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="K2K.css" />
		<title>Key To Key - conditions générales</title>
		<link rel="icon" type="image/gif" href="Img/icone.gif" />


	</head>
</head>

<body>
		<h1>Conditions Générales</h1>
		<p>MERCI DE LIRE ATTENTIVEMENT LES PRESENTES CONDITIONS GENERALES DE SERVICES, CAR ELLES CONTIENNENT DES INFORMATIONS IMPORTANTES CONCERNANT VOS DROITS, RECOURS ET OBLIGATIONS. ELLES INCLUENT DIFFERENTES LIMITATIONS ET EXCLUSIONS, UNE CLAUSE D’ATTRIBUTION DE COMPETENCE EN CAS DE LITIGES, AINSI QUE DES OBLIGATIONS RELATIVES AU RESPECT DES LOIS ET REGLEMENTS APPLICABLES.</p>

<p>LES HOTES DOIVENT NOTAMMENT COMPRENDRE COMMENT LES LOIS S’APPLIQUENT DANS LEUR VILLE. CERTAINES VILLES DISPOSENT DE LOIS LIMITANT LEUR CAPACITE A HEBERGER DES VOYAGEURS PAYANTS SUR DE COURTES PERIODES. CES LOIS SONT SOUVENT INSCRITES DANS LES REGLEMENTS D’URBANISME OU ADMINISTRATIFS. DANS DE NOMBREUSES VILLES, LES HOTES DOIVENT SE FAIRE ENREGISTRER, OBTENIR UNE AUTORISATION OU UNE LICENCE AVANT DE PROPOSER UN BIEN OU D’ACCEPTER DES VOYAGEURS. CERTAINS TYPES DE RESERVATION DE COURTE DUREE PEUVENT ETRE TOTALEMENT INTERDITS. L’APPLICATION DE CES LOIS VARIE EN FONTION DES AUTORITES LOCALES. LES SANCTIONS PEUVENT COMPRENDRE DES PEINES D'AMENDES OU AUTRES. LES HOTES DOIVENT PRENDRE CONNAISSANCE DES LOIS LOCALES AVANT DE PROPOSER UNE ANNONCE D’HEBERGEMENT SUR Key2Key.</p>

<p>Dernière mise à jour: 16 décembre 2014</p>

</body>
</html>